
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int kleen = 7;
  public static final int cadena = 15;
  public static final int conjunto = 12;
  public static final int comenMulti = 17;
  public static final int puntoYcoma = 5;
  public static final int flecha = 3;
  public static final int or = 8;
  public static final int dos_puntos = 2;
  public static final int comenSimple = 16;
  public static final int llaveAbre = 9;
  public static final int digito = 13;
  public static final int EOF = 0;
  public static final int id = 14;
  public static final int llaveCierra = 10;
  public static final int error = 1;
  public static final int concatenar = 6;
  public static final int porciento = 11;
  public static final int suma = 18;
  public static final int del_al = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dos_puntos",
  "flecha",
  "del_al",
  "puntoYcoma",
  "concatenar",
  "kleen",
  "or",
  "llaveAbre",
  "llaveCierra",
  "porciento",
  "conjunto",
  "digito",
  "id",
  "cadena",
  "comenSimple",
  "comenMulti",
  "suma"
  };
}

