
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int kleen = 8;
  public static final int raro = 20;
  public static final int cadena = 16;
  public static final int conjunto = 13;
  public static final int coma = 19;
  public static final int puntoYcoma = 6;
  public static final int or = 9;
  public static final int dos_puntos = 2;
  public static final int llaveAbre = 10;
  public static final int guion = 3;
  public static final int digito = 14;
  public static final int EOF = 0;
  public static final int id = 15;
  public static final int llaveCierra = 11;
  public static final int mayorque = 4;
  public static final int error = 1;
  public static final int concatenar = 7;
  public static final int porciento = 12;
  public static final int interrogacion = 17;
  public static final int suma = 18;
  public static final int del_al = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dos_puntos",
  "guion",
  "mayorque",
  "del_al",
  "puntoYcoma",
  "concatenar",
  "kleen",
  "or",
  "llaveAbre",
  "llaveCierra",
  "porciento",
  "conjunto",
  "digito",
  "id",
  "cadena",
  "interrogacion",
  "suma",
  "coma",
  "raro"
  };
}

